### ISSUE TITLE
Application Logic Vulnerability allows to get marks for incorrect submission

### ISSUE THREAD

**Issue by sndpflash** [sanjaygir/javascriptninjasissues#1]
When the web app user submits a solution to the question, the question is ran on the client-side with a set of input parameters, and the output is sent to the server to check with the correct output. 

The attacker can intercept the request when the solution is submitted. Since we can see what input parameter is used to check for the solution written by the user, one can easily find the output for the input parameters and then change the incorrect output in the POST request with the correct set of outputs. This way even if the solution is incorrect, the attacker can still get marks as the server just checks for the output.

**Comment by sanjaygir** [comment]
thanks. this has now been resolved.
