### ISSUE TITLE
IDOR (Insecure Direct Object Reference) in the mySubmission Feature

### ISSUE THREAD

**Issue by sndpflash** [sanjaygir/javascriptninjasissues#3]
I found one vulnerability in this feature, it's called IDOR (Insecure Direct Object Reference) which is a type of access control vulnerability.

I used two accounts:

Sandeep: The submission is shown at the following endpoint: https://www.javascriptninjas.com/mySubmission/158

Test: https://www.javascriptninjas.com/mySubmission/159

Now I can use the test account and change the submission endpoint to /158 which is the submission of the Sandeep account, I can view his submission.

With this, the attacker can view anyone's submission by just iterating over the submission id.

**Comment by sanjaygir** [comment]
this has been fixed. thanks for finding out.
