### ISSUE TITLE
IDOR (Indirect Object Reference) - Access Control

### ISSUE THREAD

**Issue by kofhearts** [sanjaygir/javascriptninjasissues#5]
Logged-in users or unauthenticated sessions can access various admin endpoints.

Steps to reproduce:

1) Visit: https://www.javascriptninjas.com/editQuestion/28
2) Visit: https://www.javascriptninjas.com/ioGenerator
3) Visit: https://www.javascriptninjas.com/createQuestion

Remediation:

Access Control should force non-admin user and return 401 (Unauthorized)

**Comment by sanjaygir** [comment]
fixed. thanks for reporting.
