### ISSUE TITLE
IDOR (Indirect Object Reference) - MySubmission

### ISSUE THREAD

**Issue by kofhearts** [sanjaygir/javascriptninjasissues#6]
Logged in users can access all the submissions through mySubmission endpoint and enumerating the id.

Steps to Reproduce:
1) Create a new user and log in.
2) Visit: https://www.javascriptninjas.com/mySubmission/2965

Mitigation:

Implement Access Control to block users from accessing others' submissions.

**Comment by sanjaygir** [comment]
fixed
