### ISSUE TITLE
Open Redirect

### ISSUE THREAD

**Issue by kofhearts** [sanjaygir/javascriptninjasissues#9]
There is open redirect in the ?next= parameter allowing the website to redirect to any websites.

Reproduction:
1) go to: https://www.javascriptninjas.com/users/login?next=https://www.evil.com
2) Login
3) User gets redirected to the attacker controlled website

Remediation

Make sure the next = only takes whitelisted URLS.

**Comment by sanjaygir** [comment]
fixed
